// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  var Promise, cheerio, fs, load, log, superagent;

  fs = require('fs');

  Promise = require('bluebird');

  superagent = require('superagent');

  cheerio = require('cheerio');

  log = console.log;

  load = module.exports = function(url) {
    var get, getModules, save, saveFile;
    get = function(url, autoReload, maxReloadTime) {
      return new Promise(function(resolve) {
        var _get, count;
        count = 0;
        log("Get From " + url);
        _get = function(url) {
          return superagent.get(url).end(function(err, res) {
            if (err) {
              log(err.code);
              if (autoReload && count < maxReloadTime) {
                count++;
                log("Reload(" + count + ") : " + url);
                return _get(url);
              } else {
                return log('Auto reload time exceed');
              }
            } else {
              return resolve(res);
            }
          });
        };
        return _get(url);
      });
    };
    getModules = function(res) {
      return new Promise(function(resolve) {
        var $, all;
        $ = cheerio.load(res.text);
        all = $('[href]');
        return function(attr) {
          var href, i, len, results;
          results = [];
          for (i = 0, len = all.length; i < len; i++) {
            attr = all[i];
            results.push((href = attr.href, href && !href.match(/^https:|^http:/) ? resovle(url + href, false) : void 0)(attr.attribs));
          }
          return results;
        };
      });
    };
    save = function(res) {
      var $;
      $ = cheerio.load(res.text);
      $('igm').remove();
      $('script').remove();
      return info(res.req.path);
    };
    saveFile = function(path, htmlStr) {
      return fs.writeFile(path, html, function(err) {
        return log(err ? err : path + " save success");
      });
    };
    return get(url, true, 10).then(getModules).then(get).then(save);
  };

  load('https://nodejs.org/docs/latest-v0.12.x/api/');

}).call(this);

//# sourceMappingURL=loadApi.js.map
