// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  var async, cheerio, fs, loadApi, log, pathpath, superagent;

  fs = require('fs');

  async = require('async');

  superagent = require('superagent');

  cheerio = require('cheerio');

  pathpath = require('path');

  log = console.log;

  loadApi = function(url) {
    var get, getModules, save, saveFile;
    get = function(url, autoReload, maxReloadTime, cb) {
      return function(cb) {
        var _get, count;
        count = 0;
        log("get from " + url);
        _get = function(url) {
          return superagent.get(url).end(function(err, res) {
            if (err) {
              log(err.code);
              if (autoReload && count < maxReloadTime) {
                count++;
                log("reload(" + count + ") : " + url);
                return _get(url);
              } else {
                return log('Auto reload time exceed');
              }
            } else {
              if (cb != null) {
                return cb(null, res);
              } else {
                return save(res);
              }
            }
          });
        };
        _get(url);
      };
    };
    getModules = function(res) {
      var $, all, attr, getHref, i, len;
      $ = cheerio.load(res.text);
      all = $('[href]');
      getHref = function(attr) {
        var href;
        href = attr.href;
        if (href && !href.match(/^http:|^https:/)) {
          return get(url + href, false, 0)();
        }
      };
      for (i = 0, len = all.length; i < len; i++) {
        attr = all[i];
        getHref(attr.attribs);
      }
    };
    save = function(res) {
      var $;
      $ = cheerio.load(res.text);
      $('img').remove();
      $('script').remove();
      saveFile(res.req.path, $.html());
    };
    saveFile = function(path, htmlStr) {
      fs.writeFile(pathpath.join('./', path), htmlStr, function(err) {
        return log(err ? err : path + " save success");
      });
    };
    return async.waterfall([get('https://nodejs.org/api/', true, 10), getModules], function(err, result) {
      log(err);
      return log(result);
    });
  };

  loadApi('https://nodejs.org/api/');

}).call(this);

//# sourceMappingURL=loadApi.js.map
