// Generated by CoffeeScript 1.10.0
(function() {
  var http, server;

  http = require('http');

  server = http.createServer();

  server.on('connection', function(c) {});

  server.listen(9999, function() {
    return console.log('Start');
  });

}).call(this);

//# sourceMappingURL=net.js.map
