// Generated by CoffeeScript 1.10.0
(function() {
  var c, echarge, i, invoiceDto, j, k, len, len1, ncharge;

  invoiceDto = AR.controller.ArCreateDetail.invoiceAmendDtoList[0];

  echarge = invoiceDto.existingChargeList;

  ncharge = invoiceDto.newAddedChargeList;

  for (i = j = 0, len = echarge.length; j < len; i = ++j) {
    c = echarge[i];
    if (c != null) {
      if (i % 2 === 0) {
        c.splitTo = 1;
      } else {
        c.splitTo = 2;
      }
    }
  }

  for (i = k = 0, len1 = ncharge.length; k < len1; i = ++k) {
    c = ncharge[i];
    if (c != null) {
      if (i % 2 === 0) {
        c.splitTo = 1;
      } else {
        c.splitTo = 2;
      }
    }
  }

  ArBillingAdjustmentDetailDwrBean.doSplit(AR.controller.ArCreateDetail.invoiceAmendDtoList, true, null, 'test split', AR.getApplication().getController('BillingAdjustmentDetail').afterConfirm);

}).call(this);

//# sourceMappingURL=test.js.map
