// Generated by CoffeeScript 1.10.0
(function() {
  var log;

  log = console.log;

  log('start load cache2');

  setTimeout(function() {
    return log('load cache2 done');
  }, 2000);

}).call(this);

//# sourceMappingURL=cache2.js.map
