// Generated by CoffeeScript 1.10.0
(function() {
  var createAndConfigureApp, express, http, log, serverSetup;

  (function(setupLodash) {
    GLOBAL._ = require('lodash');
    _.str = require('underscore.string');
    return _.mixin(_.str.exports());
  })(this);

  express = require('express');

  http = require('http');

  log = require('winston');

  serverSetup = require('./server_setup');

  module.exports.startServer = function() {
    var app;
    app = createAndConfigureApp();
    http.createServer(app).listen(app.get('port'));
    log.info('Express SSL server listening on port ' + app.get('port'));
    return app;
  };

  createAndConfigureApp = function() {
    var app;
    serverSetup.setupLogging();
    serverSetup.connectToDatabase();
    serverSetup.setupMailchimp();
    app = express();
    serverSetup.setExpressConfigurationOptions(app);
    serverSetup.setupMiddleware(app);
    serverSetup.setupRoutes(app);
    return app;
  };

}).call(this);

//# sourceMappingURL=server.js.map
